[tools]
node = "24"
elm = "0.19.1"
pnpm = "11"

[tasks.lint]
run = "pnpm run format"

[tasks."build:css"]
run = "pnpm run css"

[tasks."build:compile"]
run = "pnpm run compile"

[tasks.build]
depends = ["lint", "build:*"]

[tasks.test]
run = "pnpm run test"

[tasks.dev]
depends = ["build", "test"]

[tasks.serve]
run = "pnpm run serve"
