name: Elm CI for running tests and deploying to Github Pages

on:
  pull_request:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Elm
        uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1

      - name: Compile project
        run: elm make src/Main.elm

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.18'

      - name: Install and run elm-test
        run: |
          echo "Running elm-format and elm-test..."
          npm install
          npm run format
          npm run test

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest

    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Elm
        uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.18'

      - name: Compile and minimize project
        run: |
          echo "Compiling Elm to JavaScript"
          npm install
          ./build.sh

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      - name: Deploy to dragonwasrobot.com/brainfuck
        id: deployment
        uses: actions/deploy-pages@v4
